export const WORKFLOW_PRIORITY = {
  CRITICAL: 3,
  HIGH: 2,
  MEDIUM: 1,
  LOW: 0
};

export const TASK_TYPES = {
  BORDEREAU_SCAN: 'BORDEREAU_SCAN',
  BS_VALIDATION: 'BS_VALIDATION',
  RECLAMATION: 'RECLAMATION',
  VIREMENT: 'VIREMENT'
};

export const SLA_TIMEFRAMES = {
  SCAN: 24, // hours
  VALIDATION: 48,
  RECLAMATION: 72,
  PAYMENT: 96
};