export enum Statut {
  EN_ATTENTE = 'EN_ATTENTE',
  A_SCANNER = 'A_SCANNER',
  SCAN_EN_COURS = 'SCAN_EN_COURS',
  SCANNE = 'SCANNE',
  A_AFFECTER = 'A_AFFECTER',
  ASSIGNE = 'ASSIGNE',
  EN_COURS = 'EN_COURS',
  TRAITE = 'TRAITE',
  PRET_VIREMENT = 'PRET_VIREMENT',
  VIREMENT_EN_COURS = 'VIREMENT_EN_COURS',
  VIREMENT_EXECUTE = 'VIREMENT_EXECUTE',
  VIREMENT_REJETE = 'VIREMENT_REJETE',
  CLOTURE = 'CLOTURE',
  EN_DIFFICULTE = 'EN_DIFFICULTE',
  PARTIEL = 'PARTIEL'
}